AWSTemplateFormatVersion: "2010-09-09"

####### PARAMETERS
Parameters:
  env:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod

  space:
    Type: String
    AllowedPattern: ^[a-z0-9]+$

  BastionHostRoute53Zone:
    Type: AWS::Route53::HostedZone::Id

####### RESOURCES
Resources:
  BastionHostRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub "${env}-${space}-BastionHost-Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: update-route53-record
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: ["route53:ChangeResourceRecordSets", "route53:GetHostedZone"]
                Resource: !Sub "arn:aws:route53:::hostedzone/${BastionHostRoute53Zone}"

  BastionHostInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref BastionHostRole

####### OUTPUTS
Outputs:
  BastionHostRole:
    Description: BastionHostInstanceProfile
    Value: !Ref BastionHostInstanceProfile