name: Release
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setup cfn-lint
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint

      - name: Validate Cloudformation templates
        run: cfn-lint -I ./stacks/**/*.yaml

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Cloudformation package
        run: |
          aws cloudformation package \
          --template-file "./stacks/network.yaml" \
          --s3-prefix "public/network/nested" \
          --output-template "network-stack.json" \
          --s3-bucket ${{ secrets.BUCKET }} \
          --region us-east-1

          aws s3 cp "network-stack.json" "s3://${{ secrets.BUCKET }}/public/network/network-latest.yml"
          aws s3 cp "network-stack.json" "s3://${{ secrets.BUCKET }}/public/network/network-$(date '+%Y-%m-%d').yml"